//
//  FailureReportBuilder.swift
//  Crosswire
//
//  This file is part of Crosswire.
//
//  Crosswire is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Crosswire is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Crosswire.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation
import CrosswireKit

/// Builds the human-readable report body for an abnormal program exit. Pure
/// function — no UI, no side effects.
///
/// Consumed by `CrosswireTelemetry.scrubbedReport(for:)`, which scrubs PII and
/// attaches it to a consent-gated crash report. The body itself avoids embedding
/// raw filesystem paths so it carries no PII even before the scrub pass.
enum FailureReportBuilder {
    /// Hard cap on the body length, so an attached report stays modest in size.
    private static let maxBodyChars = 6000
    /// Tail size for the run log.
    private static let logTailLines = 150

    static func buildBody(for report: ProgramRunReport) -> String {
        var sections: [String] = []

        sections.append("**App:** `\(report.executableURL.lastPathComponent)`")
        sections.append("**Bottle:** \(report.bottleDisplayName)")
        sections.append("**Exit code:** \(report.exitCode)")
        sections.append("**Ran for:** \(String(format: "%.1f", report.duration))s")

        sections.append("\n### Environment")
        sections.append(environmentSection(for: report))

        sections.append("\n### Run log tail (last \(logTailLines) lines)")
        sections.append("```")
        sections.append(logTail(from: report.logFileURL))
        sections.append("```")

        sections.append("\n---")
        sections.append("_Auto-generated by Crosswire's failure reporter._")

        var body = sections.joined(separator: "\n")
        if body.count > maxBodyChars {
            // Trim the log section first; preserve the meta + env header.
            let suffix = "\n\n_(log truncated; see the full log in Crosswire's Logs folder)_"
            body = String(body.prefix(maxBodyChars - suffix.count)) + suffix
        }
        return body
    }

    private static func environmentSection(for report: ProgramRunReport) -> String {
        var lines: [String] = []
        let osVersion = ProcessInfo.processInfo.operatingSystemVersion
        lines.append("- **macOS:** "
                     + "\(osVersion.majorVersion).\(osVersion.minorVersion).\(osVersion.patchVersion)")
        if let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String,
           let build = Bundle.main.infoDictionary?["CFBundleVersion"] as? String {
            lines.append("- **Crosswire:** \(appVersion) (build \(build))")
        }
        if let engineVersion = CrosswireEngine.engineVersion()?.description {
            lines.append("- **Engine:** \(engineVersion)")
        }
        // Bottle config from disk so the report works even if the Bottle
        // object is gone by the time the user clicks Report.
        let metadataURL = report.bottleURL
            .appending(path: "Metadata")
            .appendingPathExtension("plist")
        if let settings = try? BottleSettings.decode(from: metadataURL) {
            lines.append("- **Windows version:** \(settings.windowsVersion.pretty())")
            lines.append("- **DXVK:** \(settings.dxvk ? "on" : "off")")
        }
        return lines.joined(separator: "\n")
    }

    private static func logTail(from url: URL?) -> String {
        guard let url else { return "(no log file located)" }
        guard let data = try? Data(contentsOf: url),
              let text = String(data: data, encoding: .utf8)
        else { return "(could not read the run log)" }
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        let tail = lines.suffix(logTailLines)
        return tail.joined(separator: "\n")
    }
}
